version: "3.9"

services:
  app:
    container_name: es_api
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - ${API_PORT}:${API_PORT}
      - "3444:3444"
    networks:
      - backend
    env_file:
      - .env

  db:
    container_name: es_db
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    networks:
      - backend
    env_file:
      - .env

networks:
  backend:
    driver: bridge
