name: Run Tests on PR

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Run build
        run: npm run build

      - name: Run Jest tests
        run: npm test

      - name: Finish PR if tests pass
        if: ${{ success() }}
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.ACTION_GITHUB_TOKEN }}
          pull-request-number: ${{ github.event.pull_request.number }}
          merge-method: merge
